ambient = [1,1,1]

[[objects]]
pt = [1, -1, 3]
r2 = 1
material.diffuse = [0.5, 1, 0.5]
material.luminous = [0,0,0]

[[objects]]
pt = [1, 1, 3]
r2 = 1
material.diffuse = [0.5, 0.5, 1]
material.luminous = [0,0,0]

[[objects]]
pt = [-1, -1, 3]
r2 = 1
material.diffuse = [1, 0.5, 0.5]
material.luminous = [0,0,0]

[[objects]]
pt = [-1, 1, 3]
r2 = 1
material.diffuse = [0.5, 0.5, 0.5]
material.luminous = [5,5,5]
